import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=''>
        <div className='flex flex-col justify-center items-center h-screen'>
          <h1 className='text-6xl font-bold text-slate-900'>Logic</h1>
          <h3 className='text-2xl mt-8 text-slate-900'>
            Next.js, TailwindCSS,
          </h3>
        </div>
      </main>
    </>
  )
}
