import Head from 'next/head'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import { useSession } from 'next-auth/react'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session, status } = useSession()
  const loading = status === 'loading'
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main className='flex flex-col justify-center items-center h-screen'>
        {session && (
          <>
            <p style={{ marginBottom: '10px' }}>
              Welcome, {session.user.name ?? session.user.email}
            </p>
          </>
        )}
        {!session && (
          <>
            <h1 className='text-6xl font-bold text-slate-900'>Logic</h1>
            <h3 className='text-2xl mt-8 text-slate-900'>please sign in</h3>
          </>
        )}
        {/* <div className='flex flex-col justify-center items-center h-screen'>
          <h1 className='text-6xl font-bold text-slate-900'>Logic</h1>
          <h3 className='text-2xl mt-8 text-slate-900'>
            Next.js, TailwindCSS,
          </h3>

        </div> */}
      </main>
    </>
  )
}
